version: '3.7'
services:
  server:
    build:
      context: ./backend
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./backend:/app
    # command: npm start
    container_name: ${SERVER_CONTAINER_NAME}
  client:
    build:
      context: ./frontend
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app
    container_name: ${CLIENT_CONTAINER_NAME}
  mysql:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: